# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=50)),
                ('article_text', models.CharField(max_length=10000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name_text', models.CharField(max_length=50)),
                ('event_detail_text', models.CharField(max_length=10000)),
                ('event_creation_date', models.DateTimeField(verbose_name='date published')),
                ('event_occurence_date', models.DateTimeField(verbose_name='Date of event')),
            ],
        ),
    ]
